Repository 9renpoto/rn, pull requests merged in 2019-10, with the labels that each got.

#661 Revert "Update dependency react-native-elements to v1.2.6"
  package.json
  yarn.lock
Labels: size/S

#662 fix: skip minor update
  renovate.json
Labels: size/XS

#665 :tea:
  .eslintrc.json
  apps/web/next.config.js
  babel.config.js
  package.json
  packages/atoms/src/story.tsx
  yarn.lock
Labels: size/L

#668 Update story.tsx
  packages/templates/src/story.tsx
Labels: size/M

#676 Added github actions
  .github/workflows/nodejs.yml
  README.md
Labels: size/S

#680 feat: Added stylelint
  .github/workflows/nodejs.yml
  package.json
  packages/templates/src/Layout.tsx
  packages/templates/src/index.ts
  packages/templates/src/story.tsx
  yarn.lock
Labels: size/XL

#677 add: formik yup
  package.json
  packages/templates/src/Formik.tsx
  packages/templates/src/index.ts
  packages/templates/src/story.tsx
  yarn.lock
Labels: size/L
